version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: restuarant-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-restuarant_db}
      POSTGRES_USER: ${POSTGRES_USER:-restuarant_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-restuarant_password}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restuarant-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-restuarant_user} -d ${POSTGRES_DB:-restuarant_db}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: restuarant-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - restuarant-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  # RabbitMQ Message Queue
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: restuarant-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin123}
    ports:
      - '5672:5672' # AMQP port
      - '15672:15672' # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - restuarant-network
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: restuarant-auth-service
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://${POSTGRES_USER:-restuarant_user}:${POSTGRES_PASSWORD:-restuarant_password}@postgres:5432/${POSTGRES_DB:-restuarant_db}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-1d}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-admin}:${RABBITMQ_PASSWORD:-admin123}@rabbitmq:5672
      REDIS_URL: redis://redis:6379
    volumes:
      - ./node_modules:/app/node_modules
      - ./apps/auth:/app/apps/auth
      - ./libs:/app/libs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json
    networks:
      - restuarant-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  # restuarant API Service
  restuarant-api-service:
    build:
      context: .
      dockerfile: apps/restuarant-api/Dockerfile
    container_name: restuarant-api-service
    ports:
      - '3002:3002'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://${POSTGRES_USER:-restuarant_user}:${POSTGRES_PASSWORD:-restuarant_password}@postgres:5432/${POSTGRES_DB:-restuarant_db}
      AUTH_SERVICE_URL: http://auth-service:3001
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-admin}:${RABBITMQ_PASSWORD:-admin123}@rabbitmq:5672
      REDIS_URL: redis://redis:6379
    volumes:
      - ./node_modules:/app/node_modules
      - ./apps/restuarant-api:/app/apps/restuarant-api
      - ./libs:/app/libs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json
    networks:
      - restuarant-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth-service:
        condition: service_started
    restart: unless-stopped

  # API Gateway Service
  gateway-service:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: restuarant-gateway-service
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      AUTH_SERVICE_URL: http://auth-service:3001
      restuarant_SERVICE_URL: http://restuarant-api-service:3002
      REDIS_URL: redis://redis:6379
    volumes:
      - ./node_modules:/app/node_modules
      - ./apps/gateway:/app/apps/gateway
      - ./libs:/app/libs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json
    networks:
      - restuarant-network
    depends_on:
      auth-service:
        condition: service_started
      restuarant-api-service:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local

networks:
  restuarant-network:
    driver: bridge
